#!/usr/bin/env node

var program = require('commander');
var inquirer = require('inquirer');

require('colors');
var configManager = new require('./lib/config.manager')();

configManager.load()
	.then(function() {
		program
		  .version('0.1.0')
		  .option('-e, --env <env>', 'Environment [staging]', /^(prod|staging)$/i, 'staging')
		;
		return configManager.buildOptions(program);	
	})
	.then(function() {
		program.parse(process.argv);
		return configManager.runBuild(program);	
	})
	.catch(function (err) {
		console.error((err + '').red);
		console.error('Abording.'.red);
		process.exit(1);
	})
;


